# Generated by Django 3.0.5 on 2020-04-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='img_url',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
