# Generated by Django 3.0.5 on 2020-04-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='gender',
            new_name='is_female',
        ),
    ]
