# Generated by Django 3.0.5 on 2020-04-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0002_auto_20200430_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
