# Generated by Django 3.0.5 on 2020-04-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0002_myuser_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='Rating',
            field=models.FloatField(default=0.0, max_length=256),
        ),
    ]
