# Generated by Django 3.0.5 on 2020-04-12 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0002_auto_20200410_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitrating',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='visitrating',
            name='rated_date',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurantapi.DateMatch'),
            preserve_default=False,
        ),
    ]
