# Generated by Django 3.0.5 on 2020-04-13 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0003_auto_20200412_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrating',
            name='rated_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurantapi.DateMatch'),
        ),
    ]
