# Generated by Django 3.0.5 on 2020-04-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0004_auto_20200413_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='Cost_for_two',
            new_name='Avg_cost',
        ),
    ]
