# Generated by Django 3.0.5 on 2020-04-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0005_auto_20200413_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datematch',
            name='timeofvisit',
            field=models.TimeField(),
        ),
    ]
